export enum SeeMeClientExceptions {
  API_KEY_MISSING = 'API_KEY_MISSING',
  API_HOST_MISSING = 'API_HOST_MISSING',
  API_HOST_PROTOCOL_UNSUPPORTED = 'API_HOST_PROTOCOL_UNSUPPORTED',
  API_PATH_INVALID = 'API_PATH_INVALID',
  SETIP_INVALID_IP = 'SETIP_INVALID_IP'
}
