export enum SeeMeClientExceptions {
  API_KEY_MISSING = 'API_KEY_MISSING',
  API_HOST_MISSING = 'API_HOST_MISSING',
  API_HOST_PROTOCOL_UNSUPPORTED = 'API_HOST_PROTOCOL_UNSUPPORTED',
  API_PATH_INVALID = 'API_PATH_INVALID',
  SETIP_INVALID_IP = 'SETIP_INVALID_IP',
  SMS_MESSAGE_MISSING = 'SMS_MESSAGE_INVALID',
  SMS_MESSAGE_STATUS_WITHOUT_CALLBACK_URL = 'SMS_MESSAGE_STATUS_WITHOUT_CALLBACK_URL'
}
